config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get :hello_world, to: 'pages#hello_world'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def page_title(title)
    content_for(:title) { title.to_s }
  end

  def page_meta_description(meta_description)
    content_for(:meta_description) { meta_description.to_s }
  end

  def yield_or_default(section, default = '')
    content_for?(section) ? content_for(section) : default
  end
end

app/views/layouts/application.html.slim
doctype html
html lang=I18n.locale.to_s data-default-lang=I18n.default_locale
  head
    title= yield_or_default :title, action_name.titlecase

    / Required meta tags
    meta charset='utf-8'
    meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'
    meta name='description' content=yield(:meta_description)

    = csrf_meta_tags
    = yield :head

    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

    / Web App manifest
    link href='/manifest.json' rel='manifest'
    meta content=t('app_name') name='Rails 5 Starter App'
    meta content='#e00000' name='theme-color'

    link href='launcher-icon-4x.png' rel='apple-touch-icon' sizes='180x180'

    / Placed at the top of the document 'cause of turbolinks
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    == render 'shared/navbar'

    .main-container.container= yield

    == render 'shared/footer'

app/views/pages/hello_world.html.slim
- page_title 'Hello World'

app/views/pages/home.html.slim
- page_title t('app_name')
- page_meta_description t('meta_description')

h1.mt-3
  = yield :title
  small< 0.0.1
ul.list-inline.lead
  li.list-inline-item
    | Ruby
    small.text-muted< 2.5.1
  li.list-inline-item
    | Rails
    small.text-muted< 5.2.0
  li.list-inline-item
    | Bootstrap
    small.text-muted< 4.1.1
  li.list-inline-item
    | Font Awesome (SVG)
    small.text-muted< 5.1.0-11

app/views/shared/_footer.html.slim
footer.main-footer
  .container
    hr
    p
      = link_to 'https://github.com/diowa/ruby2-rails5-bootstrap-heroku' do
        span.fab.fa-github> aria-hidden='true'
        span.sr-only GitHub
        | diowa/ruby2-rails5-bootstrap-heroku

app/views/shared/_navbar.html.slim
nav.main-navbar.navbar.main-navbar.navbar-light.bg-light.navbar-expand-lg
  .container
    = link_to t('app_name'), root_path, class: 'navbar-brand'
    button.navbar-toggler.navbar-toggler-right type='button' data-toggle='collapse' data-target='#main-navbar-collapse' aria-controls='main-navbar-collapse' aria-expanded='false' aria-label=t('.toggle_navigation')
      span.navbar-toggler-icon
    #main-navbar-collapse.collapse.navbar-collapse
      ul.navbar-nav.main-navbar-nav.ml-auto
        li.nav-item= link_to 'Hello World', hello_world_path, class: 'nav-link'